details:
  name: React
  repository_name: unit-react

sequence:
  Rendering & Interactivity:
    - name: Unit 3 Launch
      elements:
        - kind: deck
        - kind: recording
    - name: NPM for React
      pursuit_path: npm-for-react
      kind: lesson
      activity: ~ # none
    - name: Introduction to React
      pursuit_path: intro-to-react
      kind: lesson
      activity: repository
    - name: React Props
      pursuit_path: react-props
      kind: lesson
      activity: repository
    - name: React State - Booleans, Numbers & Strings
      pursuit_path: react-state-primitive-values
      kind: lesson
      activity: repository
    - name: React State - Objects
      pursuit_path: react-state-objects
      kind: lesson
      activity: ~ # none, continue last lab
    - name: React Forms
      pursuit_path: react-forms
      kind: lesson
      activity: repository
    - name: React Lifting State
      pursuit_path: react-lifting-state
      kind: lesson
      activity: repository
    - name: React Deployment
      pursuit_path: react-deployment
      kind: lesson
      activity: ~ # none coming soon
    - name: Bird Sanctuary Project
      pursuit_path: bird-sanctuary
      kind: project
      activity: repository
      points: 7
    - name: Introduction to Bootstrap with React
      pursuit_path: intro-to-bootstrap-w-react
      kind: lesson
      activity: repository
      starter: intro-to-bootstrap-w-react
    - name: App Polishing
      pursuit_path: app-polishing
      kind: lesson
      activity: ~
    - name: React Student Dashboard
      pursuit_path: student-dashboard
      activity: repository
      kind: project
      points: 10
  Asynchronous Actions:
    - name: React Lifecycle Methods & Networking in React
      pursuit_path: react-lifecycle-networking
      kind: lesson
      activity: repository
    - name: Routing in React
      pursuit_path: react-router
      kind: lesson
      activity: repository
    - name: React CRUD (Multi-part lesson and lab)
      pursuit_path: react-crud
      kind: lesson
      activity: repository
      starter: television-shows-api
  Application Development:
    - name: Collaboration with GitHub
      pursuit_path: collaboration-with-github
      kind: lesson
      activity: ~ #none
    - name: Merge Conflicts
      pursuit_path: merge-conflicts
      kind: lesson
      activity: ~ # none
    - name: Project Workflow with Teams
      elements:
        - kind: reading
          pursuit_path: project-workflow
        - kind: recording
    - name: React YouTube Clone Project
      pursuit_path: youtube-clone
      kind: project
      activity: repository
      points: 7
    - name: Final Assessment
      pursuit_path: final-react
      kind: assessment
      activity: repository
      points: 26
    - name: Bonus - Convert Classes to Hooks
      pursuit_path: react-classes-to-hooks
      kind: lesson
      activity: repository
    - name: End of Module Reflection
      elements:
        - kind: deck
        - kind: recording
